// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: guessio.proto
#ifndef GRPC_guessio_2eproto__INCLUDED
#define GRPC_guessio_2eproto__INCLUDED

#include "guessio.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace guessio {

// gRPC Service
class GuessService final {
 public:
  static constexpr char const* service_full_name() {
    return "guessio.GuessService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::guessio::JoinReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>> AsyncJoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>>(AsyncJoinGameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>> PrepareAsyncJoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>>(PrepareAsyncJoinGameRaw(context, request, cq));
    }
    virtual ::grpc::Status MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::guessio::GuessReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>> AsyncMakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>>(AsyncMakeGuessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>> PrepareAsyncMakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>>(PrepareAsyncMakeGuessRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>* AsyncJoinGameRaw(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::guessio::JoinReply>* PrepareAsyncJoinGameRaw(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>* AsyncMakeGuessRaw(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::guessio::GuessReply>* PrepareAsyncMakeGuessRaw(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::guessio::JoinReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>> AsyncJoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>>(AsyncJoinGameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>> PrepareAsyncJoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>>(PrepareAsyncJoinGameRaw(context, request, cq));
    }
    ::grpc::Status MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::guessio::GuessReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>> AsyncMakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>>(AsyncMakeGuessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>> PrepareAsyncMakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>>(PrepareAsyncMakeGuessRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response, std::function<void(::grpc::Status)>) override;
      void JoinGame(::grpc::ClientContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response, std::function<void(::grpc::Status)>) override;
      void MakeGuess(::grpc::ClientContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>* AsyncJoinGameRaw(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::guessio::JoinReply>* PrepareAsyncJoinGameRaw(::grpc::ClientContext* context, const ::guessio::JoinRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>* AsyncMakeGuessRaw(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::guessio::GuessReply>* PrepareAsyncMakeGuessRaw(::grpc::ClientContext* context, const ::guessio::GuessRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_JoinGame_;
    const ::grpc::internal::RpcMethod rpcmethod_MakeGuess_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status JoinGame(::grpc::ServerContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response);
    virtual ::grpc::Status MakeGuess(::grpc::ServerContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_JoinGame() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinGame(::grpc::ServerContext* context, ::guessio::JoinRequest* request, ::grpc::ServerAsyncResponseWriter< ::guessio::JoinReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MakeGuess() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMakeGuess(::grpc::ServerContext* context, ::guessio::GuessRequest* request, ::grpc::ServerAsyncResponseWriter< ::guessio::GuessReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_JoinGame<WithAsyncMethod_MakeGuess<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_JoinGame() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::guessio::JoinRequest, ::guessio::JoinReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::guessio::JoinRequest* request, ::guessio::JoinReply* response) { return this->JoinGame(context, request, response); }));}
    void SetMessageAllocatorFor_JoinGame(
        ::grpc::MessageAllocator< ::guessio::JoinRequest, ::guessio::JoinReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::guessio::JoinRequest, ::guessio::JoinReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinGame(
      ::grpc::CallbackServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MakeGuess() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::guessio::GuessRequest, ::guessio::GuessReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::guessio::GuessRequest* request, ::guessio::GuessReply* response) { return this->MakeGuess(context, request, response); }));}
    void SetMessageAllocatorFor_MakeGuess(
        ::grpc::MessageAllocator< ::guessio::GuessRequest, ::guessio::GuessReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::guessio::GuessRequest, ::guessio::GuessReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MakeGuess(
      ::grpc::CallbackServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_JoinGame<WithCallbackMethod_MakeGuess<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_JoinGame() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MakeGuess() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_JoinGame() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinGame(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MakeGuess() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMakeGuess(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_JoinGame() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->JoinGame(context, request, response); }));
    }
    ~WithRawCallbackMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinGame(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MakeGuess() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MakeGuess(context, request, response); }));
    }
    ~WithRawCallbackMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MakeGuess(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_JoinGame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_JoinGame() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::guessio::JoinRequest, ::guessio::JoinReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::guessio::JoinRequest, ::guessio::JoinReply>* streamer) {
                       return this->StreamedJoinGame(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_JoinGame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status JoinGame(::grpc::ServerContext* /*context*/, const ::guessio::JoinRequest* /*request*/, ::guessio::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJoinGame(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::guessio::JoinRequest,::guessio::JoinReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MakeGuess : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MakeGuess() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::guessio::GuessRequest, ::guessio::GuessReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::guessio::GuessRequest, ::guessio::GuessReply>* streamer) {
                       return this->StreamedMakeGuess(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MakeGuess() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MakeGuess(::grpc::ServerContext* /*context*/, const ::guessio::GuessRequest* /*request*/, ::guessio::GuessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMakeGuess(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::guessio::GuessRequest,::guessio::GuessReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_JoinGame<WithStreamedUnaryMethod_MakeGuess<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_JoinGame<WithStreamedUnaryMethod_MakeGuess<Service > > StreamedService;
};

}  // namespace guessio


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_guessio_2eproto__INCLUDED
